stages:
    - builddcimg
    - deploy




build_dc_image:
  stage: builddcimg
  image: docker:20.10.16
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "Zzax9js2Erfevvv" | docker login --username raga70 --password-stdin
   # - docker login -u raga70 -p Zzax9js2Erfevvv # i am supper against exposing my login credentials like that but the fontys gitlab server doesnt allow masking variables
  script:
    - docker build -t raga70/djigitbetfe:latest .
    - docker push raga70/djigitbetfe:latest

deploy:
    stage: deploy
    before_script:
        - chmod 400 $SSH_KEY
        - ls -l
    script: 
        - ssh -o StrictHostKeyChecking=no -i $SSH_KEY  raga70@20.203.252.102 "
            cd djgitbet/djigitbet && echo CDintoDjigitbet && git pull && echo PULLEDfromGit &&
            echo Zzax9js2Erfevvv | sudo docker login --username raga70 --password-stdin &&
            echo LOGGED IN TO DOCKER &&
            chmod +x gradlew && sed -i -e 's/\r$//' gradlew && ./gradlew assemble &&
            sudo docker pull raga70/djigitbetfe:latest &&
            sudo docker-compose down && sudo  docker-compose up -d --build"
